#!/bin/bash

# Strict mode
set -euo pipefail
IFS=$'\n\t'


# File to write to
file=.savestate


# Show help and exit
function help_and_exit {
    echo "Usage: sast load | save | help"
    exit 1
}


# Display previous save
function load {
    if [ -e $file ]
    then
        l=`tail -n 1 $file`
        tail -n $((l+2)) $file | head -n $((l))
    else
        echo "No saved state"
    fi
}


# Write a save to file
function save {
    l=0
    if [ -e $file ]
    then
        input="\n"
    else
        input=""
    fi

    while IFS='\n' read -r line || [[ -n "$line" ]]; do
        input=$input$line"\n"
        l=$((l+1))
    done
    echo -ne $input"\n$l\n" >> $file
}


# Ensure exactly one argument is given
if [ ! $# = "1" ]
then
    help_and_exit
fi

# Match argument
case $1 in
    load)
        load
        ;;

    save)
        save
        ;;

    help)
    *)
        help_and_exit
esac
